cafe = bytes('café', encoding='utf_8')
print(cafe)
print(cafe[0])
print(cafe[:1])
cafe_arr = bytearray(cafe)
print(cafe_arr)
print(bytearray(b'caf\xc3\xa9'))
print(cafe_arr[-1:])
bytearray(b'\xa9')
print(bytearray(b'\xa9'))